apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-ml
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5.69-jdk8-openjdk-slim-buster
        ports:
        - containerPort: 8080

